name: Keep Supabase Alive

on:
  schedule:
    # Se ejecuta a las 00:00 UTC todos los domingos y miércoles
    - cron: '0 0 * * 0,3'
  workflow_dispatch: # Permite probar la acción manualmente desde GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API
        run: |
          curl -i -X GET "https://ftbyjjmvflxlotnkauwd.supabase.co/rest/v1/Encuesta?select=id&limit=1" \
            -H "apikey: sb_publishable_ut3DRPMELPw-6nCvxSbMjA_Cttmj4FA" \
            -H "Authorization: Bearer sb_publishable_ut3DRPMELPw-6nCvxSbMjA_Cttmj4FA"
